### ISSUE TITLE
about dependencies.panda_folding.panda_fold_env

### ISSUE THREAD

**Issue by zcswdt** [rlee3359/folding-by-hand#1]
Thank you so much for open-sourcing your code! I am very interested in your research and was eager to try out the code. However, while setting it up, I noticed that it seems to be missing a package. Could you possibly provide that missing package or guide me on how to obtain it? Thank you in advance for your help.
`from dependencies.panda_folding.panda_fold_env import PandaFoldEnv as Env`

**Comment by rlee3359** [comment]
Hi, thanks very much for the interest in this project. The missing package is the Panda control env, which basically takes pick and place actions in the step function and performs the folding action, returning images. 
The control of the panda is based heavily on [armer](https://github.com/qcr/armer) from my university. Many aspects of the panda control are hard coded based on our specific robot setup. You should be able to swap out all the low level control and camera parts to suit whichever set up you are using to control your robot. 

I have added the file to this repository, I hope it is helpful for you.

**Comment by zcswdt** [comment]
Thank you so much for your help and detailed explanations! The file you provided is incredibly valuable and I believe it will greatly benefit our project. I appreciate the time you took to organize and share these materials. I will carefully review them and adapt them to our specific needs. If I have any further questions, I might reach out to you again. Thank you once again for your kindness!
















At 2024-05-27 23:21:23, "Rob" ***@***.***> wrote:

Hi, thanks very much for the interest in this project. The missing package is the Panda control env, which basically takes pick and place actions in the step function and performs the folding action, returning images.
The control of the panda is based heavily on armer from my university. Many aspects of the panda control are hard coded based on our specific robot setup. You should be able to swap out all the low level control and camera parts to suit whichever set up you are using to control your robot.

I have added the file to this repository, I hope it is helpful for you.
