### ISSUE TITLE
about collect_demos.py

### ISSUE THREAD

**Issue by zcswdt** [rlee3359/folding-by-hand#3]
Excuse me, I noticed in your dataset collection process that depth maps, RGB images, and infrared images have been collected. However, I did not see any alignment operations in the code. Without alignment, how can the temporal consistency of these three types of data be ensured?

**Comment by rlee3359** [comment]
Are you referring to temporal synchronization of the images? I save one frame per action at a very low frequency, and don't recall having any issues with temporal synchronization with the L515 camera.

**Comment by zcswdt** [comment]
> Are you referring to temporal synchronization of the images? I save one frame per action at a very low frequency, and don't recall having any issues with temporal synchronization with the L515 camera.

Yes, you understood it correctly. The question is about the alignment of the depth map, RGB and infrared map in time. I don't know much about the principles of cameras. I researched some information and added the following code just in case. Thank you for your answer.

         `frames = pipeline.wait_for_frames()
            aligned_frames = align.process(frames)
            depth_frame = aligned_frames.get_depth_frame()
            color_frame = aligned_frames.get_color_frame()
            ir_frame = aligned_frames.get_infrared_frame()`

**Comment by rlee3359** [comment]
I believe the code you have added will perform spatial alignment, as in aligning the rgb with the depth so that they look similar, since they have different sensors with different FOV etc. I performed this manually with the key points and homography, since I have a fixed square workspace with calibrated corners.

I don't believe you need to perform any temporal synchronisation for the L515 camera.

**Comment by zcswdt** [comment]
> I don't believe you need to perform any temporal synchronisation for the L515 camera.



> I believe the code you have added will perform spatial alignment, as in aligning the rgb with the depth so that they look similar, since they have different sensors with different FOV etc. I performed this manually with the key points and homography, since I have a fixed square workspace with calibrated corners.
> 
> I don't believe you need to perform any temporal synchronisation for the L515 camera.

I roughly understand what you mean, because you crop and map to crop_keypoints. I have a question, the coordinates in rgb_keypoints and ir_keypoints are the four points you fixed on the desktop. Then, are the coordinates of the four points measured in the collected RGB image and infrared image respectively?
