### ISSUE TITLE
about rgb_keypoints

### ISSUE THREAD

**Issue by zcswdt** [rlee3359/folding-by-hand#4]
May I ask how you get your rgb_keypoints and ir_keypoints? Thank you

**Comment by rlee3359** [comment]
They are the locations of the four corners of the workspace as seen in the respective images.

**Comment by zcswdt** [comment]
I found this red working area in the RGB image, which can be obtained by measuring the image captured by the camera. But the infrared images are mostly black, and this working area cannot be seen in the images, so I didn't understand how to obtain this ir_keypoints. Thank you very much for your answer and help.

---- Replied Message ----
| From | ***@***.***> |
| Date | 06/09/2024 15:02 |
| To | rlee3359/folding-by-hand ***@***.***> |
| Cc | zcswdt ***@***.***>,
Author ***@***.***> |
| Subject | Re: [rlee3359/folding-by-hand] about rgb_keypoints (Issue #4) |

They are the locations of the four corners of the workspace as seen in the respective images.

**Comment by rlee3359** [comment]
I used markers on each corner of the workspace that were visible in IR to measure the points. I think I used red pins that reflected IR.

**Comment by zcswdt** [comment]
I think I understand now. I will also make a red point tomorrow and fix it. I should be able to work in the laboratory now. I completed the calibration of the robotic arm today. Sincerely thank you, for your contribution, I will quote and thank you.

---- Replied Message ----
| From | ***@***.***> |
| Date | 06/09/2024 22:17 |
| To | rlee3359/folding-by-hand ***@***.***> |
| Cc | zcswdt ***@***.***>,
Author ***@***.***> |
| Subject | Re: [rlee3359/folding-by-hand] about rgb_keypoints (Issue #4) |

I used markers on each corner of the workspace that were visible in IR to measure the points. I think I used red pins that reflected IR.
